name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up CMake
        uses: zaba505/setup-cmake@v1

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build
